codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 94%
        threshold: 0%
        # advanced settings
        if_ci_failed: error
        informational: false
        paths:
          - "src"
    patch:
      default:
        # basic
        target: 94%
        threshold: 0%
        # advanced settings
        if_ci_failed: error
        informational: false
        paths:
          - "src"

  precision: 2
  round: down
  range: "90...100"
